using System.ComponentModel.DataAnnotations;

namespace GZCTF.Models.Data;

/// <summary>
/// A reusable registration code, generated by a game admin, optionally tied to a single game so
/// that registering with it also auto-joins that game
/// </summary>
public class RegistrationCode
{
    public RegistrationCode() { }

    public RegistrationCode(string code, Game game, UserInfo creator)
    {
        Code = code;
        Game = game;
        GameId = game.Id;
        CreatedByUserId = creator.Id;
    }

    /// <summary>
    /// The code itself, used as the natural primary key
    /// </summary>
    [Key]
    [MaxLength(Limits.RegistrationCodeLength)]
    public string Code { get; set; } = string.Empty;

    /// <summary>
    /// Game ID this code is tied to
    /// </summary>
    [Required]
    public int GameId { get; set; }

    /// <summary>
    /// Game this code is tied to
    /// </summary>
    public Game Game { get; set; } = null!;

    /// <summary>
    /// ID of the user who generated this code
    /// </summary>
    [Required]
    public Guid CreatedByUserId { get; set; }

    /// <summary>
    /// When this code was generated
    /// </summary>
    [Required]
    public DateTimeOffset CreatedAtUtc { get; set; } = DateTimeOffset.UtcNow;
}
